In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('Bond_preprocessed.csv')

In [ ]:
#df.rename(columns = {'Default':'default'}, inplace = True)

In [ ]:
for col in df.columns:
   if df[col].dtype!='object':
        median=df[col].median()
        df[col]= df[col].fillna(value=median,axis=0)     

In [ ]:
df=df.fillna('unkown')

In [ ]:
def find_outliers_IQR(ddf):
    for i in df.columns:
        if df[i].dtype!='object':
            
            q1=df[i].quantile(0.25)

            q3=df[i].quantile(0.75)

            IQR=q3-q1
            upper_lim=q3+1.5*IQR
            lower_lim=q1-1.5*IQR
            outliers = df[i][((df[i]<(q1-1.5*IQR)) | (df[i]>(q3+1.5*IQR)))]

            outliers_lower = df[i][((df[i]<(lower_lim)))]
            df[i][outliers_lower.index]=(q1-1.5*IQR)
        
   
   
            outliers_upper = df[i][((df[i]>(upper_lim)))]
            df[i][outliers_upper.index]=(q3+1.5*IQR)
      
     
            print(i)
            print(outliers.count())

In [ ]:
find_outliers_IQR(df)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


BidsPortfolioManager
5216
BidsApi
14749
BidsManual
5381
Age
57
AppliedAmount
4194
Amount
4019
Interest
3286
LoanDuration
0
MonthlyPayment
3720
IncomeTotal
3921
ExistingLiabilities
2599
LiabilitiesTotal
3735
RefinanceLiabilities
8524
DebtToIncome
4875
FreeCash
7617
MonthlyPaymentDay
0
CreditScoreEsMicroL
11991
PrincipalPaymentsMade
5884
InterestAndPenaltyPaymentsMade
6841
PrincipalBalance
3522
InterestAndPenaltyBalance
9449
NoOfPreviousLoansBeforeLoan
11910
AmountOfPreviousLoansBeforeLoan
7665
PreviousRepaymentsBeforeLoan
12109
PreviousEarlyRepaymentsCountBeforeLoan
4340
Default
0


In [ ]:
obj_data=df.select_dtypes('object')
num_bondora=df.drop(obj_data.columns,axis=1)

In [ ]:
MutualInfoFeatures=['InterestAndPenaltyBalance','PrincipalPaymentsMade','PrincipalBalance','InterestAndPenaltyPaymentsMade','Interest','Amount','AppliedAmount','MonthlyPayment','PreviousRepaymentsBeforeLoan','BidsPortfolioManager']

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.svm import SVC
from sklearn.datasets import make_classification


In [ ]:
GB=GradientBoostingClassifier()
def GBoostModel(X,y):
     sc=StandardScaler()
     X=sc.fit_transform(X)
     X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25, random_state=0)
     GB.fit(X_train,y_train)
     y_predict=GB.predict(X_test)
     print(confusion_matrix(y_test,y_predict))
     print(classification_report(y_test,y_predict))
     print(accuracy_score(y_test, y_predict))

In [ ]:
y=df["Default"]
X=num_bondora.drop("Default", axis=1)
GBoostModel(X,y)

[[8459  211]
 [1329 9350]]
              precision    recall  f1-score   support

         0.0       0.86      0.98      0.92      8670
         1.0       0.98      0.88      0.92     10679

    accuracy                           0.92     19349
   macro avg       0.92      0.93      0.92     19349
weighted avg       0.93      0.92      0.92     19349

0.9204093234792495


In [ ]:
def Logistic_Regression(X):
    
    classifier = LogisticRegression(random_state = 0)
    
    sc=StandardScaler()
    X=sc.fit_transform(X)
    X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25, random_state=16)
    classifier.fit(X_train, y_train)
    y_pred = classifier.predict(X_test)
    print(confusion_matrix(y_test,y_pred))
    print(classification_report(y_test,y_pred))
    print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

In [ ]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics

In [ ]:
y=df["Default"]
X=num_bondora.loc[:, MutualInfoFeatures]
Logistic_Regression(X)

[[8423  210]
 [2031 8685]]
              precision    recall  f1-score   support

         0.0       0.81      0.98      0.88      8633
         1.0       0.98      0.81      0.89     10716

    accuracy                           0.88     19349
   macro avg       0.89      0.89      0.88     19349
weighted avg       0.90      0.88      0.88     19349

Accuracy: 0.8841800609850639


In [ ]:
svc=SVC()
def SVMModel(X):
   
     sc=StandardScaler()
     X=sc.fit_transform(X)
     X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25, random_state=0)
     svc.fit(X_train,y_train)
     y_predict=svc.predict(X_test)
     print(confusion_matrix(y_test,y_predict))
     print(classification_report(y_test,y_predict))
     print(accuracy_score(y_test, y_predict))

In [ ]:
SVMModel(X)

[[8549  121]
 [1350 9329]]
              precision    recall  f1-score   support

         0.0       0.86      0.99      0.92      8670
         1.0       0.99      0.87      0.93     10679

    accuracy                           0.92     19349
   macro avg       0.93      0.93      0.92     19349
weighted avg       0.93      0.92      0.92     19349

0.923975399245439


In [ ]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=45)

In [ ]:
from sklearn.pipeline import Pipeline

model_2 = Pipeline([('Scaler', StandardScaler()), ('SVC', SVC())])
model_2.fit(x_train, y_train)
model_2.score(x_test, y_test)

0.9255258669698693

In [ ]:
from sklearn.model_selection import GridSearchCV
param_grid = [
  {'SVC__C': [1, 10, 100, 1000], 'SVC__gamma': [0.01, 0.001, 0.0001], 'SVC__kernel': ['rbf']},
 ]
grid = GridSearchCV(model_2, param_grid, n_jobs=-1, verbose=True)
grid.fit(x_train, y_train)

# Get the best Parameters and estimator
print(grid.best_params_)
print(grid.best_estimator_)
grid.score(x_test, y_test)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
{'SVC__C': 1000, 'SVC__gamma': 0.01, 'SVC__kernel': 'rbf'}
Pipeline(steps=[('Scaler', StandardScaler()), ('SVC', SVC(C=1000, gamma=0.01))])


0.946457181249677